name: Python flask App
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flask8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: py test
        run: |
          pip install pytest
          export PYTHONPATH=src
          pytest
      - name: create docker image
        if: github.ref == 'refs/heads/master' && job.status == 'success'
        run: |
          docker build . -f Dockerfile -t adamcao/ciciflaskapp:3.0
      - name: login to docker
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PWD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PWD
      - name: push to docker hub
        run: |
          docker push adamcao/ciciflaskapp:3.0
